<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="8" passed="4" failed="4" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-06-25T07:56:47 IST" name="sample" finished-at="2022-06-25T07:59:23 IST" duration-ms="155627">
    <groups>
    </groups>
    <test started-at="2022-06-25T07:56:47 IST" name="Login" finished-at="2022-06-25T07:57:18 IST" duration-ms="30706">
      <class name="com.inetbanking.testcases.TC_Login_001">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.inetbanking.testcases.TC_Login_001@2b91004a]" started-at="2022-06-25T07:56:47 IST" name="setup" finished-at="2022-06-25T07:56:53 IST" duration-ms="5573" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="loginTest()[pri:0, instance:com.inetbanking.testcases.TC_Login_001@2b91004a]" started-at="2022-06-25T07:56:53 IST" name="loginTest" finished-at="2022-06-25T07:57:14 IST" duration-ms="21871" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.inetbanking.testcases.TC_Login_001@2b91004a]" started-at="2022-06-25T07:57:14 IST" name="teardown" finished-at="2022-06-25T07:57:18 IST" duration-ms="3220" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.inetbanking.testcases.TC_Login_001 -->
    </test> <!-- Login -->
    <test started-at="2022-06-25T07:57:18 IST" name="Datadriven" finished-at="2022-06-25T07:59:10 IST" duration-ms="111972">
      <class name="com.inetbanking.testcases.TC_loginDatadriven_002">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.inetbanking.testcases.TC_loginDatadriven_002@290222c1]" started-at="2022-06-25T07:57:18 IST" name="setup" finished-at="2022-06-25T07:57:25 IST" duration-ms="6732" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="logindatadriven(java.lang.String,java.lang.String)[pri:0, instance:com.inetbanking.testcases.TC_loginDatadriven_002@290222c1]" started-at="2022-06-25T07:57:26 IST" name="logindatadriven" data-provider="logindata" finished-at="2022-06-25T07:57:46 IST" duration-ms="20349" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr373218]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[vAbejat]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at com.inetbanking.testcases.TC_loginDatadriven_002.logindatadriven(TC_loginDatadriven_002.java:31)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logindatadriven -->
        <test-method signature="logindatadriven(java.lang.String,java.lang.String)[pri:0, instance:com.inetbanking.testcases.TC_loginDatadriven_002@290222c1]" started-at="2022-06-25T07:57:46 IST" name="logindatadriven" data-provider="logindata" finished-at="2022-06-25T07:57:54 IST" duration-ms="7974" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr366465]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[gedytar2]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at com.inetbanking.testcases.TC_loginDatadriven_002.logindatadriven(TC_loginDatadriven_002.java:31)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logindatadriven -->
        <test-method signature="logindatadriven(java.lang.String,java.lang.String)[pri:0, instance:com.inetbanking.testcases.TC_loginDatadriven_002@290222c1]" started-at="2022-06-25T07:57:54 IST" name="logindatadriven" data-provider="logindata" finished-at="2022-06-25T07:58:15 IST" duration-ms="20705" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr373218]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[vAbejat]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at com.inetbanking.testcases.TC_loginDatadriven_002.logindatadriven(TC_loginDatadriven_002.java:31)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logindatadriven -->
        <test-method signature="logindatadriven(java.lang.String,java.lang.String)[pri:0, instance:com.inetbanking.testcases.TC_loginDatadriven_002@290222c1]" started-at="2022-06-25T07:58:15 IST" name="logindatadriven" data-provider="logindata" finished-at="2022-06-25T07:58:43 IST" duration-ms="28276" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr373218]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[vAbejat]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at com.inetbanking.testcases.TC_loginDatadriven_002.logindatadriven(TC_loginDatadriven_002.java:31)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logindatadriven -->
        <test-method signature="logindatadriven(java.lang.String,java.lang.String)[pri:0, instance:com.inetbanking.testcases.TC_loginDatadriven_002@290222c1]" started-at="2022-06-25T07:58:43 IST" name="logindatadriven" data-provider="logindata" finished-at="2022-06-25T07:59:07 IST" duration-ms="23830" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr416902]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[ujUruqA]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logindatadriven -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.inetbanking.testcases.TC_loginDatadriven_002@290222c1]" started-at="2022-06-25T07:59:07 IST" name="teardown" finished-at="2022-06-25T07:59:10 IST" duration-ms="3001" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.inetbanking.testcases.TC_loginDatadriven_002 -->
    </test> <!-- Datadriven -->
    <test started-at="2022-06-25T07:59:10 IST" name="sample_verify" finished-at="2022-06-25T07:59:23 IST" duration-ms="12830">
      <class name="com.inetbanking.testcases.TC_Sample_Verify">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.inetbanking.testcases.TC_Sample_Verify@47d9a273]" started-at="2022-06-25T07:59:10 IST" name="setUp" finished-at="2022-06-25T07:59:16 IST" duration-ms="6191" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testVerifyTitle()[pri:1, instance:com.inetbanking.testcases.TC_Sample_Verify@47d9a273]" started-at="2022-06-25T07:59:16 IST" name="testVerifyTitle" finished-at="2022-06-25T07:59:16 IST" duration-ms="7" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testVerifyTitle -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.inetbanking.testcases.TC_Sample_Verify@47d9a273]" started-at="2022-06-25T07:59:16 IST" name="tearDown" finished-at="2022-06-25T07:59:16 IST" duration-ms="116" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.inetbanking.testcases.TC_Sample_Verify@47d9a273]" started-at="2022-06-25T07:59:16 IST" name="setUp" finished-at="2022-06-25T07:59:22 IST" duration-ms="6093" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testLogo()[pri:2, instance:com.inetbanking.testcases.TC_Sample_Verify@47d9a273]" started-at="2022-06-25T07:59:22 IST" name="testLogo" finished-at="2022-06-25T07:59:23 IST" duration-ms="295" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogo -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.inetbanking.testcases.TC_Sample_Verify@47d9a273]" started-at="2022-06-25T07:59:23 IST" name="tearDown" finished-at="2022-06-25T07:59:23 IST" duration-ms="121" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.inetbanking.testcases.TC_Sample_Verify -->
    </test> <!-- sample_verify -->
  </suite> <!-- sample -->
</testng-results>
